### PR TITLE
Fix NtpTimeProvider

### LINKED ISSUE #37: NtpTimeProvider ignores NTP data
Thank you for this nice library!
I happen to run my app in a few devices that don't have properly sync'd clocks, which caused TOTP codes to fail.

It seemed pretty easy, just using NtpTimeProvider should do it!

Unfortunately it didn't work:
Turns out that NtpTimeProvider currently uses `timeInfo.getReturnTime()` which is the the local timestamp for the reply -- No NTP data is used at all!

The fixed code looks like this (Maybe ntpOffset could be cached?)

```
    @Override
    public long getTime() throws TimeProviderException {
        long ntpOffset = 0;
        try {
            TimeInfo timeInfo = client.getTime(ntpHost);
            timeInfo.computeDetails();
            if (timeInfo.getOffset() != null) {
                ntpOffset = timeInfo.getOffset();
                Log.i(TAG, "NTP offset to calculate TOTP is " + ntpOffset + "ms");
            } else {
                Log.w(TAG, "Unable to calculate NTP offset");
            }
        } catch (Exception e) {
            Log.w(TAG, "Failed to get NTP offset", e);
        }

        return (System.currentTimeMillis() + ntpOffset) / 1000;
    }
```

### PR DESCRIPTION
**Pull request by paulo-raca**
`timeInfo.getReturnTime()` is the _local_ timestamp of the ntp reply.

To properly use the Ntp it is needed to:
- call `timeInfo.computeDetails()` to compute the NTP offset
- Add `timeInfo.getOffset()` to the local timestamp

This PR fix #37

### CODE REVIEW

File: totp/src/main/java/dev/samstevens/totp/time/NtpTimeProvider.java [hunk 1]
```diff
@@ -37,13 +37,19 @@ private NtpTimeProvider(String ntpHostname, int timeout, String dependentClass)
...
-
-            return (long) Math.floor(timeInfo.getReturnTime() / 1000L);
+            timeInfo = client.getTime(ntpHost);
+            timeInfo.computeDetails();
         } catch (Exception e) {
             throw new TimeProviderException("Failed to provide time from NTP server. See nested exception.", e);
         }
+
+        if (timeInfo.getOffset() == null) {
+            throw new TimeProviderException("Failed to calculate NTP offset", null);
```
Comment (samdjstevens) [inline totp/src/main/java/dev/samstevens/totp/time/NtpTimeProvider.java:49]:
```suggestion
            throw new TimeProviderException("Failed to calculate NTP offset");
```

Since you added the message only constructor can we drop the null here?

**Review by samdjstevens — CHANGES_REQUESTED** [review]
Thanks for this PR! Just one small suggestion then will be happy to merge

File: totp/src/main/java/dev/samstevens/totp/time/NtpTimeProvider.java (hunk 1 above)
Comment (paulo-raca) [reply totp/src/main/java/dev/samstevens/totp/time/NtpTimeProvider.java:49]: That was the idea 🤦‍♂️

**Comment by samdjstevens** [comment]
Merged, thanks!
